AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Ignore method length in test files
Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
